name: arcaurora-cursors
build-base: core26
base: bare
license: GPL-3.0
version: '1.1'

platforms:
  all:
    build-on: [amd64]
    build-for: [all]

summary: Arc Aurora Cursors
description: |
	This snap contains the Arc Aurora Cursors Theme from  yeyushengfan258 (https://github.com/yeyushengfan258/ArcAurora-Cursors). Arc Aurora Cursors is an x-cursor theme inspired by macOS and based on capitaine-cursors.

grade: stable
confinement: strict

slots:
  icon-themes:
    interface: content
    content: icon-themes
    source:
      read:
        - $SNAP/share/icons/ArcAurora-cursors

parts:
  cursors:
    plugin: dump
    source: https://github.com/stoefelz/ArcAurora-Cursors/releases/download/release/ArcAurora-cursors.zip

    organize:
      ArcAurora-cursors: share/icons/ArcAurora-cursors

    prime:
      - share/icons/ArcAurora-cursors