---
name: arcaurora-cursors
version: '1.0'
base: core22
license: GPL-3.0
grade: stable
confinement: strict
summary: Arc Aurora Cursor Theme
description: |
  This snap contains the Arc Aurora Cursors Theme from  yeyushengfan258 (https://github.com/yeyushengfan258/ArcAurora-Cursors). Arc Aurora Cursors is an x-cursor theme inspired by macOS and based on capitaine-cursors.
slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/ArcAurora-cursors
parts:
  cursors:
    plugin: dump
    source: ./ArcAurora-cursors.zip
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
      mv -f $SNAPCRAFT_PART_INSTALL/ArcAurora-cursors $SNAPCRAFT_PART_INSTALL/share/icons/
    stage:
      - share/icons/ArcAurora-cursors
